### ISSUE TITLE
Organização

### ISSUE THREAD

**Issue by JacksonOsvaldo** [rafael-rfzorzi/OpenGlacX_Oficinas#1]
Fala, Rafael. Tudo tranquilo?

Cara, achei bem legal a ideia do teu projeto. No entanto, acho que a gente pode melhorar a maneira como as coisas estão organizadas. O que acha?

Que tal tentarmos alinhar e/ou adequar o projeto seguindo as diretrizes da Python Foundation ou do nosso querido (e odiado) PEP 8? Além disso, acho que seria interessante tantarmos, de maneira rasa, "modularizar" toda aplicação seguindo algum(uns) padrão(ões) de projeto. O que acha?

Referências
1 - [PEP8](https://www.python.org/dev/peps/pep-0008/)
2 - [Padrões de Projeto em Python](url)

**Comment by rafael-rfzorzi** [comment]
Oi Jackson, agradeço o feedback.
Sim , já penso nisso faz um tempo, porém como é comum acontecer, outras
prioridades vão entrando na frente, mas a ideia é essa mesma, deixar o
codigo mais clean, dentro dos padrões, pra melhorar a manutenção e
legibilidade.
Mais uma vez agradeço o feedback e fico a disposição.
